---
kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: amd64

clone:
  disable: true

steps:
- name: clone
  commands:
  - cd /srv/salty
  - git checkout main
  - git pull

- name: salt apply
  commands:
  - salt '*' state.apply test=true